### ISSUE TITLE
Add additional "Numerical Differentiation" - functions

### ISSUE THREAD

**Issue by Freymaurer** [CSBiology/FSharp.Stats#19]
**Is your feature request related to a problem? Please describe.**
It can become very complicated to derive e.g. an erfcx(x) function, so it can be nice to have an approximation. 

**Describe the solution you'd like**
I want to implement the numerical differentiation function with a method to calculate an "optimal" window h, over which the differentiation is done.

**Describe alternatives you've considered**
MatLab can do the calculate the derivative of an erfcx(x)-function, but only for set numbers and not variables. 

**Additional context** 
Everything is set and ready, the PR is coming. 👍

**Comment by ZimmerD** [comment]
closed due to merging of #20

**Comment by ZimmerD** [comment]
closed due to merging of #20
