### ISSUE TITLE
[BUG] Pearson correlation fails with long int input 

### ISSUE THREAD

**Issue by omaus** [CSBiology/FSharp.Stats#35]
### Description

When using int collections as input sequences the output can be wrong or NaN due to int overflow.

### Repro steps

let x1 = Array.init 1000 id |> FSharp.Stats.Array.shuffleFisherYates
let x2 = Array.init 1000 id |> FSharp.Stats.Array.shuffleFisherYates
let y1 = x1 |> Array.map float
let y2 = x2 |> Array.map float

FSharp.Stats.Correlation.Seq.pearson y1 y2
FSharp.Stats.Correlation.Seq.pearson x1 x2 // gives a different output than above because of int overflow

let a1 = Array.init 10000 id |> FSharp.Stats.Array.shuffleFisherYates
let a2 = Array.init 10000 id |> FSharp.Stats.Array.shuffleFisherYates
let b1 = a1 |> Array.map float
let b2 = a2 |> Array.map float

FSharp.Stats.Correlation.Seq.pearson b1 b2
FSharp.Stats.Correlation.Seq.pearson a1 a2 // gives a NaN

### Known workarounds

Convert input sequences from int to float. Internal float conversion should be done at an earlier point.

**Comment by bvenn** [comment]
closed by c8ae564
