### ISSUE TITLE
[BUG] Rank.rankAverage returns wrong results in some cases

### ISSUE THREAD

**Issue by HLWeil** [CSBiology/FSharp.Stats#49]
**To Reproduce**

```
[|2.0; 3.0; 4.0; 5.0; 5.0; 5.0|]
|> Rank.rankAverage
```
returns

`val it : float array =  [|1.0; 2.0; 3.0; 2.666666667; 2.666666667; 2.666666667|]
`

**Expected behavior**

The result should be 

`val it : float array =  [|1.0; 2.0; 3.0; 5.0; 5.0; 5.0|] `

as the 3 fives should receive the ranks 4, 5 and 6  -> average = 5

**Comment by bvenn** [comment]
closed by 980025435b22de6991559442ecec5dcbf00c723d
