### ISSUE TITLE
Inputmatrix in Testing.RMT should be of type Matrix

### ISSUE THREAD

**Issue by HLWeil** [CSBiology/FSharp.Stats#57]
### Description

Since the Eigenvalue Decomposition of matrices was implemented in FSharp.Stats. There's no reason to have RMT.compute use Array2D as type for input matrices.

Therefore it should be changed to Matrix.

**Comment by bvenn** [comment]
closed by 77b469478f2ebfa60e78ee90f8de676954ecdf7b
