### ISSUE TITLE
[Feature Request] Additional growth curve models

### ISSUE THREAD

**Issue by bvenn** [CSBiology/FSharp.Stats#63]
To model growth curves, additional models such as Gompertz should be added to the NonlinearRegression model table.

**Comment by kMutagene** [comment]
What about the following models, are their addition of value ?

 - [ ] Richards curve
 - [ ] Weibull
 - [ ] Janoschek
 - [ ] Morgan-Mercer_Floden
 - [ ] Von Bertalanffy

They also partially seem to have adjusted versions e.g. for seasonal growth

introduction to them can be viewed [here](http://www.pisces-conservation.com/growthhelp/index.html?the_gompertz_growth_curve.htm)

**Comment by bvenn** [comment]
Gompertz documentation added by fc771294766d85c7a94df5de0320c0e9c25207d4

**Comment by bvenn** [comment]
- Richards model b10068267f9c8b64362051e30885f992354becad
  - Weibull model 206f59d3cfe91a45c8ad8117a1fd4df8e8a8aa07
  - Janoschek model 5bd975e18e939648772a645abbed7c421da92de0
  - Morgan-Mercer-Flodin model be68d8936a562e10d2d08014f5bb08ee110076ec
  - Verhulst models 7d7a0bcaccc77b3dd626fcded5be09cbd853ede8
  - von Bertalanffy model 90e649e27e551a7e0df07f662cadd3f1bbd3b8cd
  - growth curve documentation 3f87c6f7bd8ec8e228d88a952ca763430b3cca0c
